### ISSUE TITLE
你好 net

### ISSUE THREAD

**Issue by RichardsATcn** [2300070/ezpinyin#4]
ySystem.Collections.Generic.List`1[System.Object]
Unhandled exception. System.TypeInitializationException: The type initializer for 'EzPinyin.Common' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at EzPinyin.Common..cctor()
   --- End of inner exception stack trace ---
   at EzPinyin.Common.AcquireBuffer()
   at EzPinyin.PinyinHelper.GetInitial(String text, String separator)
   at Program.<>c__DisplayClass0_1.<<Main>$>b__5(String filepath, String softid) in G:\.net\rongao-sim-zbtrain-server\RASimServer\CodeFirst\Program.cs:line 184
   at Program.<Main>$(String[] args) in G:\.net\rongao-sim-zbtrain-server\RASimServer\CodeFirst\Program.cs:line 264
PS N:\CodeFirst>

**Comment by RichardsATcn** [comment]
`        ID = (PinyinHelper.GetInitial(CLASSIFY) + "_" + ID).ToUpper();
`

**Comment by AbotMe** [comment]
this issue is the same with previous one,yet it was closed before, the nuget library and code has been updated to v1.1.1, please update your reference to latest version.
